ens dona error en el test de proposal
  Then the proposal should be stored in the database                                                       # cat.udl.eps.softarch.tfgfinder.steps.ProposalStepsD
efs.the_proposal_should_be_stored_in_the_database()
      io.cucumber.core.exception.CucumberException: Step [the proposal should be stored in the database] is defined with 0 parameters at 'cat.udl.eps.softarch.t
fgfinder.steps.ProposalStepsDefs.the_proposal_should_be_stored_in_the_database()'.
However, the gherkin step has 1 arguments: